homeworks/hw4/finances/urls.py
from django.conf.urls import url

from .views import main_page, finance_page, generator_page

urlpatterns = [
    url(r'^$', main_page, name='main'),
    url(r'^charges/$', finance_page, name='finances'),
    url(r'^generator/$', generator_page, name='generator')
]

homeworks/hw4/myfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("finances.urls", namespace='finances'))
]

homeworks/hw4/finances/models.py
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models


class Charge(models.Model):
    date = models.DateField(default=datetime.today)
    value = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return "[" + str(self.date) + "] " + str(self.value)

    @staticmethod
    def get_absolute_url():
        return reverse("finances:finances")

homeworks/hw4/finances/forms.py
from decimal import Decimal
from django import forms
from .models import Charge


class ChargeForm(forms.ModelForm):
    class Meta:
        model = Charge
        fields = ('date', 'value')

    def clean(self):
        data = super().clean()
        value_of_charge = data.get('value')
        date_of_charge = data.get('date')
        if value_of_charge is None or date_of_charge is None:
            return data
        if Decimal.compare(Decimal(0), value_of_charge) == Decimal('0'):
            self.add_error("value", "Danger! Charge can't be a zero!")
        if value_of_charge < 0 and date_of_charge > date_of_charge.today():
            self.add_error("date", "Danger! You can't set negative charge on future day!")
        return data

homeworks/hw4/finances/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import ChargeForm
from .generator import random_transactions


def main_page(request):
    context = {
        "title": "Main Page"
    }
    return render(request, "main.html", context)


def finance_page(request):
    form = ChargeForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        success_message = "Successfully created new Charge(value: " + str(
            request.POST.get('value')) + ", date: " + request.POST.get('date') + ")"
        messages.success(request, success_message)
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Finances",
        "form": form
    }
    return render(request, "finances.html", context)


def generator_page(request):
    deposit = []
    withdraw = []
    for (date, value) in random_transactions():
        if value < 0:
            withdraw.append((date, value))
        else:
            deposit.append((date, value))
    context = {
        "title": "Generator",
        "deposit": deposit,
        "withdraw": withdraw
    }
    return render(request, "generator.html", context)

homeworks/hw4/finances/templates/finances.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Finance project</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href='{% url "finances:main" %}'>Main</a></li>
                    <li class="active"><a href='{% url "finances:finances" %}'>Charges</a></li>
                    <li><a href='{% url "finances:generator" %}'>Generator</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <form method="post" style="margin-top: 30px">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Add new Charge"/>
        </form>
        <br>
        <div class="panel panel-primary">
            <div class="panel-body">
                Message box
            </div>
            <div class="panel-footer">
                {% if messages %}
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>

    </div>
</body>
</html>

homeworks/hw4/finances/templates/generator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Finance project</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href='{% url "finances:main" %}'>Main</a></li>
                <li><a href='{% url "finances:finances" %}'>Charges</a></li>
                <li class="active"><a href='{% url "finances:generator" %}'>Generator</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="row-fluid">
        <div class="col-lg-6">
            <table class="table table-striped">
                <caption><h2>Your deposit operations</h2></caption>
                <tr>
                    <th>Date</th>
                    <th>Value</th>
                </tr>
                {% for date, value in deposit %}
                <tr class="success">
                    <td>{{ date }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
        <div class="col-lg-6">
            <table class="table table-striped warning">
                <caption><h2>Your withdraw operations</h2></caption>
                <tr>
                    <th>Date</th>
                    <th>Value</th>
                </tr>
                {% for date, value in withdraw %}
                <tr class="danger">
                    <td>{{ date }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>
</body>
</html>

homeworks/hw4/finances/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Finance project</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Main</a></li>
                    <li><a href='{% url "finances:finances" %}'>Charges</a></li>
                    <li><a href='{% url "finances:generator" %}'>Generator</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <h1>Hello, Welcome to the Finance project main page.</h1>
    </div>
</body>
</html>